import type { Property } from "~/models/shared";

// generate a list of moke data for properties
export const PROPERTIES_LIST: Property[] = [
  {
    id: "1",
    title: "Cozy Cottage",
    description: "A cozy cottage with a beautiful garden.",
    type: "House",
    location: "123 Maple Street, Springfield",
    sellPrice: 250000,
    rentPrice: 1200,
    isSell: true,
    availableDate: new Date("2025-03-01"),
    isPerMonth: true,
    isPerYear: false,
    userId: "user1",
    bedRooms: 3,
    bathRooms: 2,
    totalBeds: 3,
    totalArea: 1500,
    latitude: 37.7749,
    longitude: -122.4194,
    amenities: [
      { id: 1, code: "GARDEN", name: "Garden" },
      { id: 2, code: "GARAGE", name: "Garage" },
    ],
    attachments: [
      {
        attachmentId: "a1",
        fileName: "front_view.jpg",
        filePath: "/images/front_view.jpg",
      },
      {
        attachmentId: "a2",
        fileName: "garden.jpg",
        filePath: "/images/garden.jpg",
      },
    ],
  },
  {
    id: "2",
    title: "Modern Apartment",
    description: "A modern apartment in the heart of the city.",
    type: "Apartment",
    location: "456 Oak Avenue, Metropolis",
    sellPrice: 500000,
    rentPrice: 2000,
    isSell: false,
    availableDate: new Date("2025-04-01"),
    isPerMonth: true,
    isPerYear: false,
    userId: "user2",
    bedRooms: 2,
    bathRooms: 1,
    totalBeds: 2,
    totalArea: 1000,
    latitude: 40.7128,
    longitude: -74.006,
    amenities: [
      { id: 3, code: "POOL", name: "Swimming Pool" },
      { id: 4, code: "GYM", name: "Gym" },
    ],
    attachments: [
      {
        attachmentId: "b1",
        fileName: "living_room.jpg",
        filePath: "/images/living_room.jpg",
      },
      {
        attachmentId: "b2",
        fileName: "bedroom.jpg",
        filePath: "/images/bedroom.jpg",
      },
    ],
  },
  {
    id: "3",
    title: "Beach House",
    description: "A stunning beach house with ocean views.",
    type: "House",
    location: "789 Ocean Drive, Seaside",
    sellPrice: 750000,
    rentPrice: 3000,
    isSell: true,
    availableDate: new Date("2025-05-01"),
    isPerMonth: true,
    isPerYear: false,
    userId: "user3",
    bedRooms: 4,
    bathRooms: 3,
    totalBeds: 4,
    totalArea: 2000,
    latitude: 34.0194,
    longitude: -118.4912,
    amenities: [
      { id: 5, code: "BEACH", name: "Beach Access" },
      { id: 6, code: "BBQ", name: "BBQ Area" },
    ],
    attachments: [
      {
        attachmentId: "c1",
        fileName: "ocean_view.jpg",
        filePath: "/images/ocean_view.jpg",
      },
      {
        attachmentId: "c2",
        fileName: "patio.jpg",
        filePath: "/images/patio.jpg",
      },
    ],
  },
];
